import { StyleSheet } from 'react-native';
import { ThemeColors } from '@/shared/theme/colors';

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  keyboardView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
  },
  scrollContent: {
    padding: 20,
  },
  polaroidContainer: {
    alignSelf: 'center',
    width: '75%',
    aspectRatio: 1,
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.borderDark,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: colors.background === '#0c0f14' ? 0.3 : 0.05,
    shadowRadius: 8,
    elevation: 8,
    marginBottom: 24,
  },
  photoPreview: {
    width: '100%',
    height: '100%',
    borderRadius: 16,
    resizeMode: 'cover',
  },
  noPhotoPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noPhotoText: {
    color: colors.textMuted,
    marginTop: 8,
    fontWeight: '600',
  },
  inputSection: {
    marginBottom: 24,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: 10,
  },
  amountInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.borderDark,
    paddingHorizontal: 16,
  },
  amountInput: {
    flex: 1,
    height: 56,
    color: colors.text,
    fontSize: 22,
    fontWeight: 'bold',
  },
  currencyText: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: 'bold',
  },
  notesInput: {
    backgroundColor: colors.inputBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.borderDark,
    padding: 16,
    color: colors.text,
    fontSize: 16,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  planSelector: {
    flexDirection: 'row',
  },
  planChip: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginRight: 10,
    borderWidth: 1,
    borderColor: colors.borderDark,
  },
  planChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  planChipText: {
    color: colors.textSecondary,
    fontWeight: '600',
  },
  planChipTextActive: {
    color: colors.textLight,
    fontWeight: 'bold',
  },
  lockedPlan: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.borderDark,
    padding: 16,
  },
  lockedPlanText: {
    color: colors.textMuted,
    marginLeft: 8,
    fontWeight: '600',
  },
  noPlansWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 159, 67, 0.1)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 159, 67, 0.3)',
    padding: 16,
  },
  noPlansWarningText: {
    color: colors.primary,
    marginLeft: 8,
    fontWeight: '600',
  },
  visibilityContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  visibilityChip: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: colors.borderDark,
    flexDirection: 'row',
  },
  visibilityActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  visibilityText: {
    fontSize: 10,
    color: colors.textSecondary,
    marginLeft: 6,
    fontWeight: '600',
  },
  visibilityTextActive: {
    color: colors.textLight,
    fontWeight: 'bold',
  },
  saveBtn: {
    backgroundColor: colors.primary,
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 40,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  saveBtnText: {
    color: colors.textLight,
    fontSize: 18,
    fontWeight: 'bold',
  },
});
